#!/bin/bash
#
# chkconfig: 35 90 12
# description: gearbox services
#
# Get function from functions library
. /etc/init.d/functions

BASEDIR=/var/gearbox/gearbox-workers

export PATH=$PATH:/command
create() {
    # separate out create into it's own function and call it at rpm install
    # time as well as start time so that changes to config files will
    # modify the daemontools run scripts when you call 'service gearbox
    # restart'
    action "Creating gearbox services: " \
    gearbox-svc-builder --file=/etc/gearbox/gearbox.conf \
                        --key=daemons \
                        --prefix=gearbox- \
                        --service_dir=$BASEDIR
}

start() {
    # call create to rewrite the daemontools run files in case the config
    # files have changed
    create

    # if we stopped it with svc -d (in the stop function) start it with svc -u
    if svstat $BASEDIR/* | grep -q down; then
        action "Waiting 5 secs for svscan to spawn supervise for new services" \
            sleep 5
        action "Starting gearbox services: " svc -u $BASEDIR/*
    fi
}

status() {
    shopt -s nullglob
    workers=($BASEDIR/*)

    if [ ${#workers[@]} -gt 0 ]; then
        svstat ${workers[*]} | grep -q down
        SV_STATUS=$?
        if [[ $SV_STATUS -eq 0 ]]; then
            echo "worker(s) down..."
            svstat ${workers[*]} | grep down | sed 's/^/    /'
            exit 1
        fi
    else
        echo "no files in $BASEDIR..."
        exit 1
    fi
}

stop() {
    shopt -s nullglob
    workers=($BASEDIR/*)
    if [ ${#workers[@]} -gt 0 ]; then
        action "Stopping gearbox services: " svc -d ${workers[*]}
    else
        echo "no files in $BASEDIR..."
        exit 1
    fi
}

delete() {
    # check if services are in starting mode. We need to allow them to
    # start completely for cleanup in delete operation
    if svstat $BASEDIR/* | \
        grep -q "unable to open supervise"; then
        # any service is not created completely, wait for them to be created
        action  "Waiting 5 secs for supervise to be spawned for new services" \
            sleep 5
    fi

    # Create an empty daemons json string
    echo '{ "daemons": [] }' > /tmp/empty-daemons.conf

    action "Deleting gearbox services: " \
        gearbox-svc-builder --file=/tmp/empty-daemons.conf \
                --key=daemons \
                --prefix=gearbox- \
                --service_dir=$BASEDIR
    rm -f /tmp/empty-daemons.conf
}

case "$1" in
    create)
        create
        ;;
    start)
        start
        ;;
    delete)
        delete
        ;;
    stop)
        stop
        ;;
    restart|reload)
        stop
        sleep 1
        start
        ;;
    status)
  		status
  		;;
    *)
        echo "Usage: $0 {create|start|stop|restart|reload|delete|status}"
        exit 1
        ;;
esac
