#!/usr/bin/env phprun
<?

require_once("Gearbox.php");
require_once("GearboxErrors.php");
require_once("test-trivial.php");

PLAN(570);

OK( $err = new ERR_MULTIPLE_CHOICES("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 300 );
IS( $err->getMessage(), "ERR_MULTIPLE_CHOICES: err");
IS( $err->getName(), "MULTIPLE_CHOICES" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_MULTIPLE_CHOICES: err" );
OK( $bycode = new ERR_CODE_300("err") );
OK( is_subclass_of($bycode, "ERR_MULTIPLE_CHOICES") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 300 );
IS( $bycode->getMessage(), "ERR_MULTIPLE_CHOICES: err");
IS( $bycode->getName(), "MULTIPLE_CHOICES" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_MULTIPLE_CHOICES: err" );

OK( $err = new ERR_MOVED_PERMANENTLY("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 301 );
IS( $err->getMessage(), "ERR_MOVED_PERMANENTLY: err");
IS( $err->getName(), "MOVED_PERMANENTLY" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_MOVED_PERMANENTLY: err" );
OK( $bycode = new ERR_CODE_301("err") );
OK( is_subclass_of($bycode, "ERR_MOVED_PERMANENTLY") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 301 );
IS( $bycode->getMessage(), "ERR_MOVED_PERMANENTLY: err");
IS( $bycode->getName(), "MOVED_PERMANENTLY" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_MOVED_PERMANENTLY: err" );

OK( $err = new ERR_MOVED_TEMPORARILY("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 302 );
IS( $err->getMessage(), "ERR_MOVED_TEMPORARILY: err");
IS( $err->getName(), "MOVED_TEMPORARILY" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_MOVED_TEMPORARILY: err" );
OK( $bycode = new ERR_CODE_302("err") );
OK( is_subclass_of($bycode, "ERR_MOVED_TEMPORARILY") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 302 );
IS( $bycode->getMessage(), "ERR_MOVED_TEMPORARILY: err");
IS( $bycode->getName(), "MOVED_TEMPORARILY" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_MOVED_TEMPORARILY: err" );

OK( $err = new ERR_SEE_OTHER("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 303 );
IS( $err->getMessage(), "ERR_SEE_OTHER: err");
IS( $err->getName(), "SEE_OTHER" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_SEE_OTHER: err" );
OK( $bycode = new ERR_CODE_303("err") );
OK( is_subclass_of($bycode, "ERR_SEE_OTHER") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 303 );
IS( $bycode->getMessage(), "ERR_SEE_OTHER: err");
IS( $bycode->getName(), "SEE_OTHER" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_SEE_OTHER: err" );

OK( $err = new ERR_NOT_MODIFIED("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 304 );
IS( $err->getMessage(), "ERR_NOT_MODIFIED: err");
IS( $err->getName(), "NOT_MODIFIED" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_NOT_MODIFIED: err" );
OK( $bycode = new ERR_CODE_304("err") );
OK( is_subclass_of($bycode, "ERR_NOT_MODIFIED") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 304 );
IS( $bycode->getMessage(), "ERR_NOT_MODIFIED: err");
IS( $bycode->getName(), "NOT_MODIFIED" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_NOT_MODIFIED: err" );

OK( $err = new ERR_USE_PROXY("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 305 );
IS( $err->getMessage(), "ERR_USE_PROXY: err");
IS( $err->getName(), "USE_PROXY" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_USE_PROXY: err" );
OK( $bycode = new ERR_CODE_305("err") );
OK( is_subclass_of($bycode, "ERR_USE_PROXY") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 305 );
IS( $bycode->getMessage(), "ERR_USE_PROXY: err");
IS( $bycode->getName(), "USE_PROXY" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_USE_PROXY: err" );

OK( $err = new ERR_TEMPORARY_REDIRECT("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 307 );
IS( $err->getMessage(), "ERR_TEMPORARY_REDIRECT: err");
IS( $err->getName(), "TEMPORARY_REDIRECT" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_TEMPORARY_REDIRECT: err" );
OK( $bycode = new ERR_CODE_307("err") );
OK( is_subclass_of($bycode, "ERR_TEMPORARY_REDIRECT") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 307 );
IS( $bycode->getMessage(), "ERR_TEMPORARY_REDIRECT: err");
IS( $bycode->getName(), "TEMPORARY_REDIRECT" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_TEMPORARY_REDIRECT: err" );

OK( $err = new ERR_BAD_REQUEST("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 400 );
IS( $err->getMessage(), "ERR_BAD_REQUEST: err");
IS( $err->getName(), "BAD_REQUEST" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_BAD_REQUEST: err" );
OK( $bycode = new ERR_CODE_400("err") );
OK( is_subclass_of($bycode, "ERR_BAD_REQUEST") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 400 );
IS( $bycode->getMessage(), "ERR_BAD_REQUEST: err");
IS( $bycode->getName(), "BAD_REQUEST" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_BAD_REQUEST: err" );

OK( $err = new ERR_UNAUTHORIZED("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 401 );
IS( $err->getMessage(), "ERR_UNAUTHORIZED: err");
IS( $err->getName(), "UNAUTHORIZED" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_UNAUTHORIZED: err" );
OK( $bycode = new ERR_CODE_401("err") );
OK( is_subclass_of($bycode, "ERR_UNAUTHORIZED") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 401 );
IS( $bycode->getMessage(), "ERR_UNAUTHORIZED: err");
IS( $bycode->getName(), "UNAUTHORIZED" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_UNAUTHORIZED: err" );

OK( $err = new ERR_PAYMENT_REQUIRED("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 402 );
IS( $err->getMessage(), "ERR_PAYMENT_REQUIRED: err");
IS( $err->getName(), "PAYMENT_REQUIRED" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_PAYMENT_REQUIRED: err" );
OK( $bycode = new ERR_CODE_402("err") );
OK( is_subclass_of($bycode, "ERR_PAYMENT_REQUIRED") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 402 );
IS( $bycode->getMessage(), "ERR_PAYMENT_REQUIRED: err");
IS( $bycode->getName(), "PAYMENT_REQUIRED" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_PAYMENT_REQUIRED: err" );

OK( $err = new ERR_FORBIDDEN("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 403 );
IS( $err->getMessage(), "ERR_FORBIDDEN: err");
IS( $err->getName(), "FORBIDDEN" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_FORBIDDEN: err" );
OK( $bycode = new ERR_CODE_403("err") );
OK( is_subclass_of($bycode, "ERR_FORBIDDEN") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 403 );
IS( $bycode->getMessage(), "ERR_FORBIDDEN: err");
IS( $bycode->getName(), "FORBIDDEN" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_FORBIDDEN: err" );

OK( $err = new ERR_NOT_FOUND("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 404 );
IS( $err->getMessage(), "ERR_NOT_FOUND: err");
IS( $err->getName(), "NOT_FOUND" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_NOT_FOUND: err" );
OK( $bycode = new ERR_CODE_404("err") );
OK( is_subclass_of($bycode, "ERR_NOT_FOUND") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 404 );
IS( $bycode->getMessage(), "ERR_NOT_FOUND: err");
IS( $bycode->getName(), "NOT_FOUND" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_NOT_FOUND: err" );

OK( $err = new ERR_METHOD_NOT_ALLOWED("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 405 );
IS( $err->getMessage(), "ERR_METHOD_NOT_ALLOWED: err");
IS( $err->getName(), "METHOD_NOT_ALLOWED" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_METHOD_NOT_ALLOWED: err" );
OK( $bycode = new ERR_CODE_405("err") );
OK( is_subclass_of($bycode, "ERR_METHOD_NOT_ALLOWED") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 405 );
IS( $bycode->getMessage(), "ERR_METHOD_NOT_ALLOWED: err");
IS( $bycode->getName(), "METHOD_NOT_ALLOWED" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_METHOD_NOT_ALLOWED: err" );

OK( $err = new ERR_NOT_ACCEPTABLE("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 406 );
IS( $err->getMessage(), "ERR_NOT_ACCEPTABLE: err");
IS( $err->getName(), "NOT_ACCEPTABLE" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_NOT_ACCEPTABLE: err" );
OK( $bycode = new ERR_CODE_406("err") );
OK( is_subclass_of($bycode, "ERR_NOT_ACCEPTABLE") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 406 );
IS( $bycode->getMessage(), "ERR_NOT_ACCEPTABLE: err");
IS( $bycode->getName(), "NOT_ACCEPTABLE" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_NOT_ACCEPTABLE: err" );

OK( $err = new ERR_PROXY_AUTHENTICATION_REQUIRED("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 407 );
IS( $err->getMessage(), "ERR_PROXY_AUTHENTICATION_REQUIRED: err");
IS( $err->getName(), "PROXY_AUTHENTICATION_REQUIRED" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_PROXY_AUTHENTICATION_REQUIRED: err" );
OK( $bycode = new ERR_CODE_407("err") );
OK( is_subclass_of($bycode, "ERR_PROXY_AUTHENTICATION_REQUIRED") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 407 );
IS( $bycode->getMessage(), "ERR_PROXY_AUTHENTICATION_REQUIRED: err");
IS( $bycode->getName(), "PROXY_AUTHENTICATION_REQUIRED" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_PROXY_AUTHENTICATION_REQUIRED: err" );

OK( $err = new ERR_REQUEST_TIME_OUT("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 408 );
IS( $err->getMessage(), "ERR_REQUEST_TIME_OUT: err");
IS( $err->getName(), "REQUEST_TIME_OUT" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_REQUEST_TIME_OUT: err" );
OK( $bycode = new ERR_CODE_408("err") );
OK( is_subclass_of($bycode, "ERR_REQUEST_TIME_OUT") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 408 );
IS( $bycode->getMessage(), "ERR_REQUEST_TIME_OUT: err");
IS( $bycode->getName(), "REQUEST_TIME_OUT" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_REQUEST_TIME_OUT: err" );

OK( $err = new ERR_CONFLICT("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 409 );
IS( $err->getMessage(), "ERR_CONFLICT: err");
IS( $err->getName(), "CONFLICT" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_CONFLICT: err" );
OK( $bycode = new ERR_CODE_409("err") );
OK( is_subclass_of($bycode, "ERR_CONFLICT") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 409 );
IS( $bycode->getMessage(), "ERR_CONFLICT: err");
IS( $bycode->getName(), "CONFLICT" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_CONFLICT: err" );

OK( $err = new ERR_GONE("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 410 );
IS( $err->getMessage(), "ERR_GONE: err");
IS( $err->getName(), "GONE" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_GONE: err" );
OK( $bycode = new ERR_CODE_410("err") );
OK( is_subclass_of($bycode, "ERR_GONE") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 410 );
IS( $bycode->getMessage(), "ERR_GONE: err");
IS( $bycode->getName(), "GONE" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_GONE: err" );

OK( $err = new ERR_LENGTH_REQUIRED("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 411 );
IS( $err->getMessage(), "ERR_LENGTH_REQUIRED: err");
IS( $err->getName(), "LENGTH_REQUIRED" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_LENGTH_REQUIRED: err" );
OK( $bycode = new ERR_CODE_411("err") );
OK( is_subclass_of($bycode, "ERR_LENGTH_REQUIRED") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 411 );
IS( $bycode->getMessage(), "ERR_LENGTH_REQUIRED: err");
IS( $bycode->getName(), "LENGTH_REQUIRED" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_LENGTH_REQUIRED: err" );

OK( $err = new ERR_PRECONDITION_FAILED("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 412 );
IS( $err->getMessage(), "ERR_PRECONDITION_FAILED: err");
IS( $err->getName(), "PRECONDITION_FAILED" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_PRECONDITION_FAILED: err" );
OK( $bycode = new ERR_CODE_412("err") );
OK( is_subclass_of($bycode, "ERR_PRECONDITION_FAILED") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 412 );
IS( $bycode->getMessage(), "ERR_PRECONDITION_FAILED: err");
IS( $bycode->getName(), "PRECONDITION_FAILED" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_PRECONDITION_FAILED: err" );

OK( $err = new ERR_REQUEST_ENTITY_TOO_LARGE("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 413 );
IS( $err->getMessage(), "ERR_REQUEST_ENTITY_TOO_LARGE: err");
IS( $err->getName(), "REQUEST_ENTITY_TOO_LARGE" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_REQUEST_ENTITY_TOO_LARGE: err" );
OK( $bycode = new ERR_CODE_413("err") );
OK( is_subclass_of($bycode, "ERR_REQUEST_ENTITY_TOO_LARGE") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 413 );
IS( $bycode->getMessage(), "ERR_REQUEST_ENTITY_TOO_LARGE: err");
IS( $bycode->getName(), "REQUEST_ENTITY_TOO_LARGE" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_REQUEST_ENTITY_TOO_LARGE: err" );

OK( $err = new ERR_REQUEST_URI_TOO_LARGE("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 414 );
IS( $err->getMessage(), "ERR_REQUEST_URI_TOO_LARGE: err");
IS( $err->getName(), "REQUEST_URI_TOO_LARGE" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_REQUEST_URI_TOO_LARGE: err" );
OK( $bycode = new ERR_CODE_414("err") );
OK( is_subclass_of($bycode, "ERR_REQUEST_URI_TOO_LARGE") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 414 );
IS( $bycode->getMessage(), "ERR_REQUEST_URI_TOO_LARGE: err");
IS( $bycode->getName(), "REQUEST_URI_TOO_LARGE" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_REQUEST_URI_TOO_LARGE: err" );

OK( $err = new ERR_UNSUPPORTED_MEDIA_TYPE("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 415 );
IS( $err->getMessage(), "ERR_UNSUPPORTED_MEDIA_TYPE: err");
IS( $err->getName(), "UNSUPPORTED_MEDIA_TYPE" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_UNSUPPORTED_MEDIA_TYPE: err" );
OK( $bycode = new ERR_CODE_415("err") );
OK( is_subclass_of($bycode, "ERR_UNSUPPORTED_MEDIA_TYPE") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 415 );
IS( $bycode->getMessage(), "ERR_UNSUPPORTED_MEDIA_TYPE: err");
IS( $bycode->getName(), "UNSUPPORTED_MEDIA_TYPE" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_UNSUPPORTED_MEDIA_TYPE: err" );

OK( $err = new ERR_RANGE_NOT_SATISFIABLE("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 416 );
IS( $err->getMessage(), "ERR_RANGE_NOT_SATISFIABLE: err");
IS( $err->getName(), "RANGE_NOT_SATISFIABLE" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_RANGE_NOT_SATISFIABLE: err" );
OK( $bycode = new ERR_CODE_416("err") );
OK( is_subclass_of($bycode, "ERR_RANGE_NOT_SATISFIABLE") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 416 );
IS( $bycode->getMessage(), "ERR_RANGE_NOT_SATISFIABLE: err");
IS( $bycode->getName(), "RANGE_NOT_SATISFIABLE" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_RANGE_NOT_SATISFIABLE: err" );

OK( $err = new ERR_EXPECTATION_FAILED("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 417 );
IS( $err->getMessage(), "ERR_EXPECTATION_FAILED: err");
IS( $err->getName(), "EXPECTATION_FAILED" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_EXPECTATION_FAILED: err" );
OK( $bycode = new ERR_CODE_417("err") );
OK( is_subclass_of($bycode, "ERR_EXPECTATION_FAILED") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 417 );
IS( $bycode->getMessage(), "ERR_EXPECTATION_FAILED: err");
IS( $bycode->getName(), "EXPECTATION_FAILED" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_EXPECTATION_FAILED: err" );

OK( $err = new ERR_UNPROCESSABLE_ENTITY("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 422 );
IS( $err->getMessage(), "ERR_UNPROCESSABLE_ENTITY: err");
IS( $err->getName(), "UNPROCESSABLE_ENTITY" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_UNPROCESSABLE_ENTITY: err" );
OK( $bycode = new ERR_CODE_422("err") );
OK( is_subclass_of($bycode, "ERR_UNPROCESSABLE_ENTITY") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 422 );
IS( $bycode->getMessage(), "ERR_UNPROCESSABLE_ENTITY: err");
IS( $bycode->getName(), "UNPROCESSABLE_ENTITY" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_UNPROCESSABLE_ENTITY: err" );

OK( $err = new ERR_LOCKED("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 423 );
IS( $err->getMessage(), "ERR_LOCKED: err");
IS( $err->getName(), "LOCKED" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_LOCKED: err" );
OK( $bycode = new ERR_CODE_423("err") );
OK( is_subclass_of($bycode, "ERR_LOCKED") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 423 );
IS( $bycode->getMessage(), "ERR_LOCKED: err");
IS( $bycode->getName(), "LOCKED" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_LOCKED: err" );

OK( $err = new ERR_FAILED_DEPENDENCY("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 424 );
IS( $err->getMessage(), "ERR_FAILED_DEPENDENCY: err");
IS( $err->getName(), "FAILED_DEPENDENCY" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_FAILED_DEPENDENCY: err" );
OK( $bycode = new ERR_CODE_424("err") );
OK( is_subclass_of($bycode, "ERR_FAILED_DEPENDENCY") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 424 );
IS( $bycode->getMessage(), "ERR_FAILED_DEPENDENCY: err");
IS( $bycode->getName(), "FAILED_DEPENDENCY" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_FAILED_DEPENDENCY: err" );

OK( $err = new ERR_UPGRADE_REQUIRED("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 426 );
IS( $err->getMessage(), "ERR_UPGRADE_REQUIRED: err");
IS( $err->getName(), "UPGRADE_REQUIRED" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_UPGRADE_REQUIRED: err" );
OK( $bycode = new ERR_CODE_426("err") );
OK( is_subclass_of($bycode, "ERR_UPGRADE_REQUIRED") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 426 );
IS( $bycode->getMessage(), "ERR_UPGRADE_REQUIRED: err");
IS( $bycode->getName(), "UPGRADE_REQUIRED" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_UPGRADE_REQUIRED: err" );

OK( $err = new ERR_INTERNAL_SERVER_ERROR("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 500 );
IS( $err->getMessage(), "ERR_INTERNAL_SERVER_ERROR: err");
IS( $err->getName(), "INTERNAL_SERVER_ERROR" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_INTERNAL_SERVER_ERROR: err" );
OK( $bycode = new ERR_CODE_500("err") );
OK( is_subclass_of($bycode, "ERR_INTERNAL_SERVER_ERROR") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 500 );
IS( $bycode->getMessage(), "ERR_INTERNAL_SERVER_ERROR: err");
IS( $bycode->getName(), "INTERNAL_SERVER_ERROR" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_INTERNAL_SERVER_ERROR: err" );

OK( $err = new ERR_NOT_IMPLEMENTED("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 501 );
IS( $err->getMessage(), "ERR_NOT_IMPLEMENTED: err");
IS( $err->getName(), "NOT_IMPLEMENTED" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_NOT_IMPLEMENTED: err" );
OK( $bycode = new ERR_CODE_501("err") );
OK( is_subclass_of($bycode, "ERR_NOT_IMPLEMENTED") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 501 );
IS( $bycode->getMessage(), "ERR_NOT_IMPLEMENTED: err");
IS( $bycode->getName(), "NOT_IMPLEMENTED" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_NOT_IMPLEMENTED: err" );

OK( $err = new ERR_BAD_GATEWAY("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 502 );
IS( $err->getMessage(), "ERR_BAD_GATEWAY: err");
IS( $err->getName(), "BAD_GATEWAY" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_BAD_GATEWAY: err" );
OK( $bycode = new ERR_CODE_502("err") );
OK( is_subclass_of($bycode, "ERR_BAD_GATEWAY") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 502 );
IS( $bycode->getMessage(), "ERR_BAD_GATEWAY: err");
IS( $bycode->getName(), "BAD_GATEWAY" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_BAD_GATEWAY: err" );

OK( $err = new ERR_SERVICE_UNAVAILABLE("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 503 );
IS( $err->getMessage(), "ERR_SERVICE_UNAVAILABLE: err");
IS( $err->getName(), "SERVICE_UNAVAILABLE" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_SERVICE_UNAVAILABLE: err" );
OK( $bycode = new ERR_CODE_503("err") );
OK( is_subclass_of($bycode, "ERR_SERVICE_UNAVAILABLE") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 503 );
IS( $bycode->getMessage(), "ERR_SERVICE_UNAVAILABLE: err");
IS( $bycode->getName(), "SERVICE_UNAVAILABLE" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_SERVICE_UNAVAILABLE: err" );

OK( $err = new ERR_GATEWAY_TIME_OUT("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 504 );
IS( $err->getMessage(), "ERR_GATEWAY_TIME_OUT: err");
IS( $err->getName(), "GATEWAY_TIME_OUT" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_GATEWAY_TIME_OUT: err" );
OK( $bycode = new ERR_CODE_504("err") );
OK( is_subclass_of($bycode, "ERR_GATEWAY_TIME_OUT") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 504 );
IS( $bycode->getMessage(), "ERR_GATEWAY_TIME_OUT: err");
IS( $bycode->getName(), "GATEWAY_TIME_OUT" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_GATEWAY_TIME_OUT: err" );

OK( $err = new ERR_VERSION_NOT_SUPPORTED("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 505 );
IS( $err->getMessage(), "ERR_VERSION_NOT_SUPPORTED: err");
IS( $err->getName(), "VERSION_NOT_SUPPORTED" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_VERSION_NOT_SUPPORTED: err" );
OK( $bycode = new ERR_CODE_505("err") );
OK( is_subclass_of($bycode, "ERR_VERSION_NOT_SUPPORTED") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 505 );
IS( $bycode->getMessage(), "ERR_VERSION_NOT_SUPPORTED: err");
IS( $bycode->getName(), "VERSION_NOT_SUPPORTED" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_VERSION_NOT_SUPPORTED: err" );

OK( $err = new ERR_VARIANT_ALSO_VARIES("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 506 );
IS( $err->getMessage(), "ERR_VARIANT_ALSO_VARIES: err");
IS( $err->getName(), "VARIANT_ALSO_VARIES" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_VARIANT_ALSO_VARIES: err" );
OK( $bycode = new ERR_CODE_506("err") );
OK( is_subclass_of($bycode, "ERR_VARIANT_ALSO_VARIES") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 506 );
IS( $bycode->getMessage(), "ERR_VARIANT_ALSO_VARIES: err");
IS( $bycode->getName(), "VARIANT_ALSO_VARIES" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_VARIANT_ALSO_VARIES: err" );

OK( $err = new ERR_INSUFFICIENT_STORAGE("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 507 );
IS( $err->getMessage(), "ERR_INSUFFICIENT_STORAGE: err");
IS( $err->getName(), "INSUFFICIENT_STORAGE" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_INSUFFICIENT_STORAGE: err" );
OK( $bycode = new ERR_CODE_507("err") );
OK( is_subclass_of($bycode, "ERR_INSUFFICIENT_STORAGE") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 507 );
IS( $bycode->getMessage(), "ERR_INSUFFICIENT_STORAGE: err");
IS( $bycode->getName(), "INSUFFICIENT_STORAGE" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_INSUFFICIENT_STORAGE: err" );

OK( $err = new ERR_NOT_EXTENDED("err") );
OK( is_subclass_of($err, "GearboxError") );
OK( is_subclass_of($err, "Exception") );
IS( $err->getCode(), 510 );
IS( $err->getMessage(), "ERR_NOT_EXTENDED: err");
IS( $err->getName(), "NOT_EXTENDED" );
IS( THROWS( function() use($err) { throw $err; } ), "ERR_NOT_EXTENDED: err" );
OK( $bycode = new ERR_CODE_510("err") );
OK( is_subclass_of($bycode, "ERR_NOT_EXTENDED") );
OK( is_subclass_of($bycode, "GearboxError") );
OK( is_subclass_of($bycode, "Exception") );
IS( $bycode->getCode(), 510 );
IS( $bycode->getMessage(), "ERR_NOT_EXTENDED: err");
IS( $bycode->getName(), "NOT_EXTENDED" );
IS( THROWS( function() use($bycode) { throw $bycode; } ), "ERR_NOT_EXTENDED: err" );

?>
